// `storybook.requires` is generated by the `withStorybook` metro wrapper when the
// bundler starts (see ../metro.config.js). It wires up the stories declared in ./main.ts
// and the decorators in ./preview.tsx.
// @ts-expect-error generated at bundle time
import { view } from './storybook.requires';
import AsyncStorage from '@react-native-async-storage/async-storage';

// AsyncStorage backs the on-device navigator + remembers the last selected story. The
// Liquid Glass Sidebar example is the landing selection. Theme switching is handled by the
// decorator in ./withFluentTheme.
//
// This app ships the full on-device UI (@storybook/react-native-ui). A lite-UI-on-glass
// variant exists at ./GlassLiteUI (wired via `CustomUIComponent: GlassLiteUI`) — note
// storybook's `liteMode` resolver is a no-op under yarn pnpm, so the lite UI must be passed
// explicitly as `CustomUIComponent`. The native Liquid Glass sidebar supersedes that JS
// approach; see packages/experimental/LiquidGlass.
const StorybookUIRoot = view.getStorybookUI({
  onDeviceUI: true,
  shouldPersistSelection: false,
  initialSelection: 'examples-native-glass-sidebar--default',
  storage: {
    getItem: AsyncStorage.getItem,
    setItem: AsyncStorage.setItem,
  },
});

export default StorybookUIRoot;
