// `storybook.requires` is generated by the `withStorybook` metro wrapper when the
// bundler starts (see ../metro.config.js). It wires up the stories declared in ./main.ts
// and the decorators in ./preview.tsx.
// @ts-expect-error generated at bundle time
import { view } from './storybook.requires';
import AsyncStorage from '@react-native-async-storage/async-storage';

// AsyncStorage backs the on-device navigator + remembers the last selected story. The
// Overview/Gallery story is used as the landing selection so a showcase of controls is
// visible on launch. Theme switching is handled by the decorator in ./withFluentTheme.
const StorybookUIRoot = view.getStorybookUI({
  onDeviceUI: true,
  shouldPersistSelection: false,
  initialSelection: 'overview-gallery--all-controls',
  storage: {
    getItem: AsyncStorage.getItem,
    setItem: AsyncStorage.setItem,
  },
});

export default StorybookUIRoot;
