/**
 * Copyright (c) Microsoft Corporation.
 * Licensed under the MIT License.
 * @format
 */
'use strict';

import { AppRegistry, LogBox } from 'react-native';

// Avoid boot-time yellowboxes interfering with the on-device Storybook UI.
LogBox.ignoreLogs([/.*deprecated.*/, /.*Platform is not supported.*/]);

// The Storybook root is assembled from `.rnstorybook/index`, which pulls in
// `storybook.requires` — a file generated by the `withStorybook` metro wrapper at
// bundle time. It is required (not statically imported) so the package's `tsc`
// build doesn't try to resolve the generated file.
// eslint-disable-next-line @typescript-eslint/no-var-requires
const StorybookUIRoot = require('../.rnstorybook').default;

AppRegistry.registerComponent('Storybook', () => StorybookUIRoot);

export default StorybookUIRoot;
