/**
 * Copyright (c) Microsoft Corporation.
 * Licensed under the MIT License.
 * @format
 */
'use strict';

import { AppRegistry, LogBox } from 'react-native';

LogBox.ignoreLogs([/.*deprecated.*/, /.*Platform is not supported.*/]);

// Full on-device Storybook UI (see metro.config.js — liteMode off). `.rnstorybook/index`
// pulls in `storybook.requires` (generated by the withStorybook metro wrapper at bundle
// time), so it is required rather than statically imported.
// eslint-disable-next-line @typescript-eslint/no-var-requires
const StorybookUIRoot = require('../.rnstorybook').default;

AppRegistry.registerComponent('Storybook', () => StorybookUIRoot);

export default StorybookUIRoot;
